{% set name = "joseki" %}
{% set version = "2.6.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/joseki-{{ version }}.tar.gz
  sha256: 1da05fddb7df3b7b3209970857128f14c4024a5437fb6c55973cdfd8ccf38c39

build:
  entry_points:
    - joseki = joseki.__main__:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.8
    - hatchling
    - pip
  run:
    - python >=3.8
    - click >=8.1.3
    - pint >=0.20.1
    - netcdf4 >=1.6.2
    - numpy >=1.22.0
    - pandas >=1.5.2
    - scipy >=1.9.3
    - xarray >=2022.12.0
    - ussa1976 >=0.3.4
    - attrs >=22.2.0
    - importlib-resources >=5.10.2

test:
  imports:
    - joseki
  commands:
    - pip check
    - joseki --help
  requires:
    - pip

about:
  home: https://github.com/rayference/joseki
  summary: Reference atmosphere's thermophysical profiles for radiative transfer applications in Earth's atmosphere.
  license: LGPLv3
  license_file: LICENSE
  doc_url: https://rayference.github.io/joseki/latest

extra:
  recipe-maintainers:
    - leroyvn
    - nollety
